### ISSUE TITLE
Question: Why is `ext-curl` a hard dependency?

### ISSUE THREAD

**Issue by ADmad** [SocialConnect/common#2]
Based on the readme it seems on can either use curl or guzzle as http client. If so why is `"ext-curl": "*"` dependency present in `composer.json`?  Having so means one wouldn't be able to install this lib if php's curl extension isn't present in one's environment.

**Comment by ovr** [comment]
Hey! Sure, you are right, possible someone will going to use guzzle adapter with `stream` wrapper, I will prepare related fix for this

Thank 😸

**Comment by ovr** [comment]
Fixed in master, released in`1.0.1`

Thank you for bug report, you are welcome

BTW: Cool avatar

![image](https://cloud.githubusercontent.com/assets/572096/24323736/d51df46a-11bd-11e7-91f1-cb697132d721.png)

**Comment by ADmad** [comment]
> BTW: Cool avatar

:sunglasses:
